spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_dashboard
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

lhv:
  jwt:
    secret: "CiltUWryHlnBnlOhZdcn6y496q6H6xF3OQeCP0pij6SJiWgkcrAAYMv32HnYTtktDDdpGT64oDrb1zvQpN7z9A=="
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 8640000